# Very important!
# Make sure that the github token has read AND WRITE access on github.
#   1. hit https://github.com/seatsio/[REPO]/settings/actions
#   2. under "Workflow permissions", make sure "Read and write permissions" is checked instead of the (default?) read only.
#

name: Release
run-name: Release ${{ github.repository }}
on:
  workflow_dispatch:
    inputs:
      versionToBump:
        description: 'The version to bump. Major for incompatible API changes, minor for adding BC features'
        required: true
        type: choice
        options:
          - minor
          - major
jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      - name: Install dependencies
        run: yarn add -D -E zx@8.1.4 semver@7.6.3
      - name: Run release script  
        run: yarn zx ./release.mjs -v $VERSION_TO_BUMP
        env:
          VERSION_TO_BUMP: ${{ inputs.versionToBump }}
          GH_TOKEN: ${{ github.token }}
      - run: pod lib lint
      - run: pod trunk push
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
